#!/bin/sh /etc/rc.common

START=99
USE_PROCD=1

start_service() {
	config_load orbien

	local enabled config
	config_get_bool enabled main enabled 0
	config_get config main config /etc/orbien/orbien.toml

	[ "$enabled" = 1 ] || return 0
	[ -s "$config" ] || return 1

	procd_open_instance
	procd_set_param command /usr/bin/orbien -c "$config"
	procd_set_param respawn
	procd_set_param stdout 1
	procd_set_param stderr 1
	procd_close_instance
}
